### ISSUE TITLE
"Commonsense_label" distribution in SICK-cured.csv doesn't seem to match with the paper.

### ISSUE THREAD

**Issue by chanr0** [huhailinguist/curing-SICK#2]
Hi,

When loading the  SICK-cured.csv, the distribution of "Commonsense_label" don't seem to match with the descriptives in section "4.3 Resulting Corpus" in Table 2 and it's the same as the "Logic_label" except for 3 sentence pairs. The distribution of the "Logic_label" seems to be fine and matches with the paper.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/72153717/206219900-4107325a-4cc9-481a-bc22-b479e787f565.png"> 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/72153717/206220048-2dfd4571-ffff-4dbf-9b84-23c9924e649b.png">

Please let me know if I misunderstood the data loading or the properties provided in the paper - Thanks!

**Comment by huhailinguist** [comment]
Uploaded [SICK_cured_20221112.csv](https://github.com/huhailinguist/curing-SICK/blob/main/SICK_cured_20221112.csv) with corrected data.
